---
# pip requirements file for building sphinx docs (e.g. nbsphinx)
version: 2

sphinx:
    configuration: docs/conf.py

# Use python 3 for building
python:
    version: 3.6
    install:
        - requirements: docs/requirements-docs.txt
